name: PHP syntax CS Fixer

on:
  pull_request:
    paths:
      - '**.php'
      - '**.phtml'

jobs:
  php-cs-fixer:
    if: "${{ ! startsWith(github.head_ref, 'release-please') || ! contains(github.event.pull_request.labels.*.name, 'autorelease: pending') }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c #v46.0.5
        id: changed-files
        with:
          files: |
            **/*.php
            **/*.phtml

      - uses: reviewdog/action-setup@e04ffabe3898a0af8d0fb1af00c188831c4b5893 #v1.3.2
        with:
          reviewdog_version: v0.20.3

#     - name: Set up PHP
#        uses: shivammathur/setup-php@0f7f1d08e3e32076e51cae65eb0b0c871405b16e #v2.34.1
#        with:
#          php-version: '8.4'

      - name: Download php-cs-fixer standalone
        run: |
          curl -L https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/latest/download/php-cs-fixer.phar -o ./php-cs-fixer
          chmod +x ./php-cs-fixer

      - name: Run php lint and report with reviewdog
        id: php-lint
        if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          files=(${{ steps.changed-files.outputs.all_changed_files }})
          {
          for file in "${files[@]}"; do
            php -l "$file"
          done 
          } 2>&1 | reviewdog \
          -efm="%m in %f on line %l" \
          -name="PHP LINT" \
          -reporter=github-pr-review \
          -level=error \
          -fail-level=error

      - name: Run php-cs-fixer and report with reviewdog
        id: php-cs-fixer
        if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          files=(${{ steps.changed-files.outputs.all_changed_files }})
          ./php-cs-fixer fix \
          --dry-run \
          --diff \
          --format=checkstyle \
          --allow-risky=yes \
          --using-cache=no "${files[@]}" \
          | reviewdog \
          -f=checkstyle \
          -name="PHP CS FIXER" \
          -reporter=github-pr-review \
          -level=error \
          -fail-level=error
