name: Magenx CI/CD - full build for release
on:
  pull_request:
    types:
      - closed
      - labeled
    branches:
      - production

  workflow_dispatch:

jobs:
  release:
    # check if PR merged and has label: release
    # if: ${{(github.event.pull_request.merged == true) && (contains(github.event.pull_request.labels.*.name, 'release'))}}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.TOKEN}}
    
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{github.ref_name}}
        
    - name: Github Actions workflow identification
      run: |
        #git config user.name "${{github.event.pull_request.user.login}}"
        #git config user.email "${{github.event.pull_request.user.login}}@users.noreply.github.com"
         git config --global user.name "Magenx CI/CD"
         git config --global user.email "magenx@users.noreply.github.com"

    # INSTALL MODULES AND UPDATES
    - name: Install modules and updates
      id: composer_install
      run: |
        composer -n -q config -g http-basic.repo.magento.com  ${{secrets.COMPOSER_USER}} ${{secrets.COMPOSER_PASSWORD}}
        composer update -W
        composer install --no-cache --no-interaction
        if [[ $? -ne 0 ]]; then
        echo "[!] Check for composer installation errors:"
        exit 1
        fi

    # SETUP DI COMPILE
    - name: Run setup:di:compile
      id: setup_di_compile
      if: ${{success()}}
      run: |
        composer dump-autoload
        bin/magento setup:di:compile -n
        if [[ $? -ne 0 ]]; then
        echo "[!] Check for compile errors:"
        exit 1
        fi
        composer dump-autoload --no-dev --optimize --apcu

    # DEPLOY STATIC FILES | CSS AND PHTML CHANGES
    - name: Deploy static files
      id: setup_static_content_deploy
      # static content deploy always
      run: |
        bin/magento setup:static-content:deploy -f -n
        if [[ $? -ne 0 ]]; then
        echo "[!] Check for static content deploy errors:"
        exit 1
        fi

    # DEBUG STEP | CHECK OUTPUTS
    - name: Debug with custom output
      id: debug
      run: |
        bin/magento
        if [[ $? -ne 0 ]]; then
        echo "[!] Check if CLI has no errors:"
        exit 1
        fi

    # SET BUILD VERSION TO ENVIRONMENT VARIABLES
    - name: Set version for complete build/release
      id: set_release_version
      if: ${{success()}}
      run: |
        echo "release_version=release_$(date +%d%m%Y_%H%M%S)" >> ${GITHUB_ENV}

    # PUSH COMPILED CODE TO BRANCH NAMED "release_version"
    - name: Push compiled code to ${{env.release_version}} branch
      id: push_to_release_version_branch
      if: ${{success()}}
      run: |
        git checkout -b ${{env.release_version}}
        git switch ${{env.release_version}}
        git add . -A
        git commit -m "${{github.sha}}"
        git push origin HEAD:${{env.release_version}} --force

    # CREATE TAG FOR THE LATEST BUILD
    - name: Create tag for the latest release
      id: tag
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: 'refs/tags/${{env.release_version}}',
            sha: context.sha
          })

    # CREATE RELEASE FROM LATEST APPROVED BUILD
    - name: Create release latest
      id: release
      if: ${{success()}}
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.repos.createRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
            tag_name: '${{env.release_version}}',
            target_commitish: '${{github.ref_name}}',
            name: '${{github.head_ref}}',
            generate_release_notes: true
          })
